# Generated by Django 5.2.6 on 2025-09-18 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_inventorystatus_purchaseabilityscore_storeapiconfig_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatorDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_requests_handled", models.PositiveIntegerField(default=0)),
                ("total_items_purchased", models.PositiveIntegerField(default=0)),
                (
                    "total_amount_processed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0.0, help_text="구매 성공률 (%)"),
                ),
                ("average_processing_time_hours", models.FloatField(default=0.0)),
                ("customer_satisfaction_score", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("max_concurrent_requests", models.PositiveIntegerField(default=10)),
                ("preferred_stores", models.JSONField(blank=True, default=list)),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "코디네이터 대시보드",
                "verbose_name_plural": "코디네이터 대시보드들",
                "db_table": "easystyle_coordinator_dashboards",
            },
        ),
        migrations.CreateModel(
            name="PurchaseProxyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("confirmed", "확인됨"),
                            ("purchasing", "구매 중"),
                            ("purchased", "구매 완료"),
                            ("shipped", "배송 중"),
                            ("delivered", "배송 완료"),
                            ("cancelled", "취소됨"),
                            ("failed", "구매 실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("normal", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                ("delivery_memo", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "service_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("coordinator_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style_recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requests",
                        to="products.stylerecommendation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "구매 대행 요청",
                "verbose_name_plural": "구매 대행 요청들",
                "db_table": "easystyle_purchase_proxy_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseProxyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=20)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("checking", "재고 확인 중"),
                            ("available", "구매 가능"),
                            ("unavailable", "구매 불가"),
                            ("ordered", "주문 완료"),
                            ("alternative_suggested", "대체품 제안"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("purchase_url", models.URLField(help_text="실제 구매할 쇼핑몰 URL")),
                (
                    "alternative_products",
                    models.JSONField(
                        blank=True, default=list, help_text="대체 상품 정보"
                    ),
                ),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateTimeField(blank=True, null=True)),
                ("coordinator_notes", models.TextField(blank=True)),
                ("customer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="products.product",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.purchaseproxyrequest",
                    ),
                ),
            ],
            options={
                "db_table": "easystyle_purchase_proxy_items",
                "ordering": ["created_at"],
                "unique_together": {("request", "product", "size")},
            },
        ),
    ]
