# Generated by Django 5.2.6 on 2025-09-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_coordinatordashboard_purchaseproxyrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproxyitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기"),
                    ("checking", "재고 확인 중"),
                    ("available", "구매 가능"),
                    ("unavailable", "구매 불가"),
                    ("ordered", "주문 완료"),
                    ("alternative_suggested", "대체품 제안"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
